version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promotion-club-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - app_storage:/storage
    depends_on:
      - db
      - redis-cache
      - redis-password-reset
  db:
    image: postgres:16-alpine
    container_name: promotion-club-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-cache:
    image: "redis:alpine"
    container_name: promotion-club-redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-password-reset:
    image: "redis:alpine"
    container_name: promotion-club-redis-password-reset
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_password_reset_data:/data

volumes:
  pgdata:
  redis_data:
  redis_password_reset_data:
  app_storage:
