version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indaiatuba-new-back-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: indaiatuba-new-back-db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: indaiatuba-new-back-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: indaiatuba-new-back-pgadmin
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@docker.com
      PGADMIN_DEFAULT_PASSWORD: docker
    depends_on:
      - db

volumes:
  pgdata:
  redis_data:
