enum Permissions {
  // do not use this permission for now
  UPDATE_USER_PERMISSIONS = "UPDATE_USER_PERMISSIONS",

  // public permissosn
  GET_ME = "GET_ME",
  SHOW_PROMOTIONS = "SHOW_PROMOTIONS",
  CREATE_QR_CODE = "CREATE_QR_CODE",
  SHOW_STORES = "SHOW_STORES",

  // store seller permissions
  CREATE_PROMOTION = "CREATE_PROMOTION",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  CREATE_IMAGE = "CREATE_IMAGE",
  VALIDATE_QR_CODE = "VALIDATE_QR_CODE",
  UPDATE_STORE = "UPDATE_STORE",
  DELETE_STORE = "DELETE_STORE",
  GET_DASHBOARD_BY_USER = "GET_DASHBOARD_BY_USER",

  // admin permissions
  UPDATE_PROMOTION = "UPDATE_PROMOTION",
  DELETE_PROMOTION = "DELETE_PROMOTION",
  SHOW_USERS = "SHOW_USERS",
  SHOW_PRODUCTS = "SHOW_PRODUCTS",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  CREATE_STORE = "CREATE_STORE",
  GET_DASHBOARD_BY_STORE = "GET_DASHBOARD_BY_STORE",
  GET_GENERAL_DASHBOARD = "GET_GENERAL_DASHBOARD",
}

export default Permissions;
