enum Permissions {
  // public permissosn
  GET_ME = "GET_ME",
  SHOW_PROMOTIONS = "SHOW_PROMOTIONS",
  CREATE_QR_CODE = "CREATE_QR_CODE",
  SHOW_STORES = "SHOW_STORES",
  SHOW_USER_PROMOTION_TICKETS = "SHOW_USER_PROMOTION_TICKETS",
  CREATE_USER_PUSH_TOKEN = "CREATE_USER_PUSH_TOKEN",

  // store seller permissions
  CREATE_PROMOTION = "CREATE_PROMOTION",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  CREATE_IMAGE = "CREATE_IMAGE",
  VALIDATE_QR_CODE = "VALIDATE_QR_CODE",
  GET_DASHBOARD_BY_USER = "GET_DASHBOARD_BY_USER",

  // admin permissions
  UPDATE_PROMOTION = "UPDATE_PROMOTION",
  DELETE_PROMOTION = "DELETE_PROMOTION",
  SHOW_INVOICES = "SHOW_INVOICES",
  CREATE_INVOICE = "CREATE_INVOICE",
  DELETE_INVOICE = "DELETE_INVOICE",
  SHOW_USERS = "SHOW_USERS",
  UPDATE_USER_PERMISSIONS = "UPDATE_USER_PERMISSIONS",
  SHOW_PRODUCTS = "SHOW_PRODUCTS",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  UPDATE_STORE = "UPDATE_STORE",
  DELETE_STORE = "DELETE_STORE",
  CREATE_STORE = "CREATE_STORE",
  GET_DASHBOARD_BY_STORE = "GET_DASHBOARD_BY_STORE",
  GET_GENERAL_DASHBOARD = "GET_GENERAL_DASHBOARD",
}

export default Permissions;
