import "reflect-metadata";

import { container } from "tsyringe";
import RepositoryProvider from "../infra/orm/repositories/providers/repository.provider";
import User from "../../modules/users/infra/orm/entities/user.entity";
import UserRepository from "../../modules/users/infra/orm/repositories/implementations/user-repository.implemetation";
import HashProvider from "../infra/hash/infra/providers/hash.provider";
import Hash from "../infra/hash/infra/implementations/hash.implementation";
import JwtProvider from "../infra/jwt/infra/provider/jwt.provider";
import Jwt from "../infra/jwt/infra/implementation/jwt.implementation";
import UserPermissions from "../../modules/users/infra/orm/entities/user-permissions.entity";
import UserPermissionsRepository from "../../modules/users/infra/orm/repositories/implementations/user-permissions-repository.implementation";
import Store from "../../modules/stores/infra/orm/entities/store.entity";
import StoreRepository from "../../modules/stores/infra/orm/repositories/implementations/store-repository.implementation";
import StoreCategory from "../../modules/stores/infra/orm/entities/store-category.entity";
import StoreCategoryRepository from "../../modules/stores/infra/orm/repositories/implementations/category-repository.implementation";
import StoreStoreCategory from "../../modules/stores/infra/orm/entities/store-store-category.entity";
import StoreStoreCategoryRepository from "../../modules/stores/infra/orm/repositories/implementations/store-category-repository.implementation";
import StoreRating from "../../modules/stores/infra/orm/entities/store-rating.entity";
import StoreRatingRepository from "../../modules/stores/infra/orm/repositories/implementations/store-rating-repository.implementation";
import StoreRatingResponse from "../../modules/stores/infra/orm/entities/store-rating-response.entity";
import StoreRatingResponseRepository from "../../modules/stores/infra/orm/repositories/implementations/store-rating-response-repository.implementation";
import Promotion from "../../modules/promotions/infra/orm/entities/promotion.entity";
import PromotionRepository from "../../modules/promotions/infra/orm/repositories/implementations/promotion-repository.implementation";
import Invoice from "../../modules/invoices/infra/orm/entities/invoice.entity";
import InvoiceRepository from "../../modules/invoices/infra/orm/repositories/implementations/invoice-repository.implementation";
import FileRepositoryProvider from "../../modules/files/infra/orm/repositories/providers/file-repository.provider";
import FileRepository from "../../modules/files/infra/orm/repositories/implementations/file-repository.implementation";
import CacheProvider from "../infra/cache/infra/providers/cache.provider";
import QrCodeCache from "../../modules/qr-code/infra/cache/implementation/qr-code-cache.implementation";
import PromotionTicket from "../../modules/tickets/infra/orm/entities/promotion-ticket.entity";
import PromotionTicketRepository from "../../modules/tickets/infra/orm/repositories/implementations/promotion-ticket-repository.implementation";
import Tags from "../../modules/promotions/infra/orm/entities/tag.entity";
import TagRepository from "../../modules/promotions/infra/orm/repositories/implementations/tag-repository.implementation";
import PromotionTag from "../../modules/promotions/infra/orm/entities/promotion-tag.entity";
import PromotionTagRepository from "../../modules/promotions/infra/orm/repositories/implementations/promotion-tag-repository.implementation";
import PromotionCategory from "../../modules/promotions/infra/orm/entities/promotion-category.entity";
import PromotionCategoryRepository from "../../modules/promotions/infra/orm/repositories/implementations/promotion-category-repository.implementation";
import PromotionPromotionCategory from "../../modules/promotions/infra/orm/entities/promotion-promotion-category.entity";
import PromotionPromotionCategoryRepository from "../../modules/promotions/infra/orm/repositories/implementations/promotion-promotion-category-repository.implementation";
import UserPushToken from "../../modules/users/infra/orm/entities/user-push-token.entity";
import UserPushTokenRepository from "../../modules/users/infra/orm/repositories/implementations/user-push-token-repository.implementation";
import UserStoreOptions from "../../modules/users/infra/orm/entities/user-store-options.entity";
import UserStoreOptionsRepository from "../../modules/users/infra/orm/repositories/implementations/user-store-options-repository.implementation";
import NotificationPusher from "../infra/push/infra/implementations/one-signal-notification-pusher.implementation";
import NotificationPusherProvider from "../infra/push/infra/providers/notification-pusher.provider";
import Benefit from "../../modules/benefits/infra/orm/entities/benefit.entity";
import BenefitRepository from "../../modules/benefits/infra/orm/repositories/implementations/benefit-repository.implementation";
import BenefitTier from "../../modules/benefits/infra/orm/entities/benefit-tier.entity";
import BenefitTierRepository from "../../modules/benefits/infra/orm/repositories/implementations/benefit-tier-repository.implementation";
import UserBenefit from "../../modules/benefits/infra/orm/entities/user-benefit.entity";
import UserBenefitRepository from "../../modules/benefits/infra/orm/repositories/implementations/user-benefit-repository.implementation";

container.registerSingleton<RepositoryProvider<User>>("UserRepository", UserRepository);
container.registerSingleton<RepositoryProvider<UserPermissions>>("UserPermissionsRepository", UserPermissionsRepository);
container.registerSingleton<RepositoryProvider<Store>>("StoreRepository", StoreRepository);
container.registerSingleton<RepositoryProvider<StoreCategory>>("StoreCategoryRepository", StoreCategoryRepository);
container.registerSingleton<RepositoryProvider<StoreStoreCategory>>("StoreStoreCategoryRepository", StoreStoreCategoryRepository);
container.registerSingleton<RepositoryProvider<StoreRating>>("StoreRatingRepository", StoreRatingRepository);
container.registerSingleton<RepositoryProvider<StoreRatingResponse>>("StoreRatingResponseRepository", StoreRatingResponseRepository);
container.registerSingleton<RepositoryProvider<Promotion>>("PromotionRepository", PromotionRepository);
container.registerSingleton<RepositoryProvider<Invoice>>("InvoiceRepository", InvoiceRepository);
container.registerSingleton<RepositoryProvider<PromotionTicket>>("PromotionTicketRepository", PromotionTicketRepository);
container.registerSingleton<RepositoryProvider<Tags>>("TagRepository", TagRepository);
container.registerSingleton<RepositoryProvider<PromotionTag>>("PromotionTagRepository", PromotionTagRepository);
container.registerSingleton<RepositoryProvider<PromotionCategory>>("PromotionCategoryRepository", PromotionCategoryRepository);
container.registerSingleton<RepositoryProvider<PromotionPromotionCategory>>(
  "PromotionPromotionCategoryRepository",
  PromotionPromotionCategoryRepository
);
container.registerSingleton<RepositoryProvider<UserPushToken>>("UserPushTokenRepository", UserPushTokenRepository);
container.registerSingleton<RepositoryProvider<UserStoreOptions>>("UserStoreOptionsRepository", UserStoreOptionsRepository);
container.registerSingleton<RepositoryProvider<Benefit>>("BenefitRepository", BenefitRepository);
container.registerSingleton<RepositoryProvider<BenefitTier>>("BenefitTierRepository", BenefitTierRepository);
container.registerSingleton<RepositoryProvider<UserBenefit>>("UserBenefitRepository", UserBenefitRepository);
container.registerSingleton<FileRepositoryProvider>("FileRepository", FileRepository);
container.registerSingleton<HashProvider>("Hash", Hash);
container.registerSingleton<JwtProvider>("Jwt", Jwt);
container.registerSingleton<CacheProvider<any>>("CacheProvider", QrCodeCache);
container.registerSingleton<NotificationPusherProvider>("NotificationPusher", NotificationPusher);
